codecov:
  require_ci_to_pass: true
  token: 9e7d993d-a9d1-4821-b0a6-a1b3807de0f6

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: true
    patch: yes
    changes: no

ignore:
  - "/android_auth_lib/src/main/java/com/blue_unicorn/android_auth_lib/ctap2/transport_specific_bindings/ble/constants"
  - "/android_auth_lib/src/main/java/com/blue_unicorn/android_auth_lib/ctap2/transport_specific_bindings/ble/exceptions"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
